### ISSUE TITLE
Support concourse environment variables in alert descriptions

### ISSUE THREAD

**Issue by geofffranks** [FidelityInternational/concourse-pagerduty-notification-resource#1]
It would be nice if this resource could make use of the built-in environment variables concourse provides for generating URLs back to the failed builds. Right now, when we specify them in the alert description, they are not evaluated, and submitted to pager duty as `$ATC_EXTERNAL_URL/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/...`

**Comment by sambryant4** [comment]
Thanks for the feedback, I agree that it would be extremely useful. I think adding this functionality as an option would be great.

**Comment by grenzr** [comment]
@geofffranks I believe a recently merged PR might help with what you originally requested.

As the README now shows in the Testing section: 'Inside the alert message you should find pipeline, job_name, concourse_build_url and output fields which contain useful error messages.'

Please let us know how you find using it, and perhaps then we can close this issue?

**Comment by geofffranks** [comment]
Yup this works for us :)
