### ISSUE TITLE
Please publish latest source code to docker hub

### ISSUE THREAD

**Issue by acatxnamedvirtue** [FidelityInternational/concourse-pagerduty-notification-resource#6]
When testing this, the team I'm on noticed that the `event_type` inside the docker container is hardcoded to `trigger`, whereas the source code here on github has it pass along the `action` parameter. The last push to docker hub was in January 2018, but the last commit in this repo was in March 2018. Please push the latest version to dockerhub, if it's stable. Thanks!

**Comment by jimconner** [comment]
Hi Tyler - New image now built and pushed to dockerhub. I think we forgot to do that when we merged in the PR back in March. Thanks for the heads-up. Cheers!!
